version: "3.4"
services:
  nextcloud:
    image: nextcloud:apache
    restart: unless-stopped
    depends_on:
      - db
      - redis
    ports:
      - 80:80
    volumes:
      - nc_data:/var/www/html
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - UPLOAD_MAX_SIZE=10G
      - OPCACHE_MEM_SIZE=256
      - APC_SHM_SIZE=256M
      - PHP_MEMORY_LIMIT=1024M
      - PHP_UPLOAD_LIMIT=10G
      
  redis:
    image: redis:alpine
    restart: unless-stopped
    expose:
      - 6379
      
  db:
    image: mariadb:10.11.5
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
    expose:
      - 3306
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/nextcloud/db_data
  nc_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/nextcloud/nc_data