version: '3'

services:
  app:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 68:68/udp
      - 82:80
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - work:/opt/adguardhome/work
      - conf:/opt/adguardhome/conf

networks:
  default:
    name: proxy
    external: true

volumes:
  work:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/adguard/work
  conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /data/adguard/conf
